# Generated by Django 5.0.3 on 2024-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_image', models.CharField(max_length=300)),
            ],
        ),
    ]
