# Generated by Django 5.0.3 on 2024-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalcost',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
